on:
  push:
    branches:
      - main
name: 🚀 Deploy update to production system
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_dev_host }}
          username: ${{ secrets.ftp_dev_user }}
          password: ${{ secrets.ftp_dev_password }}